Adding an option to color the individual density plots
sbebo/joypy pull request #49
Opened 2020-02-18 09:53 UTC by yaront

Hi @sbebo, looks like there is no option to color the individual density plots in different axes (not subgroups). The colored_group flag enables coloring the individual density plots, **only of there are no subgroups**, based in the 'I' index instead of 'j' (which is always 0 if there are no subgroups, i.e. len(group) == 1):
`if ((len(group) == 1) & (colored_groups)):
    element_color = _get_color(i, num_axes, i, num_subgroups)
else:
    element_color = _get_color(i, num_axes, j, num_subgroups)`

Before:
![Figure_1](https://user-images.githubusercontent.com/39324784/74724478-4fc9d780-520a-11ea-9ca4-060129eaa74d.png)

After:
![Figure_2](https://user-images.githubusercontent.com/39324784/74724530-5eb08a00-520a-11ea-9856-256997ac5989.png)

Thanks.

2020-02-19 22:07 UTC, leotac requested changes

2020-02-19 22:07 UTC, leotac commented on joypy/joyplot.py
> +                if ((len(group) == 1) & (colored_groups)):
If you don't mind, an advice (though I think the flag colored_group might be useless): no need for the brackets in python, and you should use "and", not &, which is the bitwise and. So:

`if len(group) == 1 and colored_groups:`

would be much more 'pythonic'.

2020-02-19 22:07 UTC, leotac commented on joypy/joyplot.py
> +                if ((len(group) == 1) & (colored_groups)):
But I'm wondering: is there a case where len(group) == 1 and colored_groups is False and `_get_color(i, num_axes, i, num_subgroups)` would be wrong? I would say no. So we could just do without that flag and just use:
`if len(group) == 1:`..

2020-02-19 22:07 UTC, leotac commented on joypy/joyplot.py
> +                if ((len(group) == 1) & (colored_groups)):
... but actually the value len(group) is already in the variable num_subgroups, which is passed to _get_color(). 

Then my overall suggestion would be:
- remove the flag `colored_groups`, I don't think it's necessary to add another flag
- move the whole logic *inside* `_get_color()`, for example replacing line 385 with:
`return color[j] if num_subgroups > 1 else color[i]`

What do you think?

2020-02-24 17:18 UTC, yaront commented on joypy/joyplot.py
> +                if ((len(group) == 1) & (colored_groups)):
Sounds excellent. Changes were implemented

2020-02-25 12:51 UTC, leotac approved these changes

2020-02-25 12:51 UTC, merged