log-normal smoothing plot_density method
sbebo/joypy pull request #64
Opened 2021-12-12 21:58 UTC by johnrsibert

Added kind = 'lognormal' to supported joyplot options

2021-12-13 22:07 UTC, leotac requested changes
Thanks for the PR!
Added some comments below. In addition to them:
- Does CFR.png needs to be committed?
- I really like the notebook example. Perhaps the `print(CFR)` could be omitted to have a cleaner output.

In general it needs some work before it can be merged.
After the improvements, the changes should also be squashed, the history is a bit messy. But I can do the squashing during the merge, no need to do it manually.

2021-12-13 22:07 UTC, leotac commented on joypy/joyplot.py
> +            sys.exit(1)
These print() and sys.exit() should be removed. The entire try/except should be removed unless we really have something useful to do in the except block.

2021-12-13 22:07 UTC, leotac commented on joypy/joyplot.py
> +           sys.exit(1)
Same here

2021-12-13 22:07 UTC, leotac commented on joypy/joyplot.py
> +
Please remove trailing spaces

2021-12-13 22:07 UTC, leotac commented on setup.py
> +      version='0.2.5.JS',
No need to change the version until a release is planned (it could be done after the PR is merged).

2021-12-13 22:07 UTC, leotac commented on joypy/__init__.py
> +__version__ = '0.2.5.JS'
No need to change the version until a new release is cut.

2021-12-13 22:07 UTC, leotac commented on joypy/__init__.py
> +__version__ = '0.2.5.JS'
(And I'm managing versions semi-automatically with bumpversion)

2021-12-13 22:07 UTC, leotac commented on joypy/joyplot.py
> +
sys shouldn't be imported

2021-12-13 22:07 UTC, leotac commented on joypy/joyplot.py
> +            floc=None,
Do these args really need to be added here, or could they be left as kwargs?

2021-12-13 22:07 UTC, leotac commented on tests/test_CFR.py
> +#!/usr/bin/env python3
If we want to test this, it should be rewritten to use pytest or (easier) simply put in a test case in test_joyplot.py
This file is not a test that can be run (it also includes a hardcoded path)

2021-12-13 22:07 UTC, leotac commented on joypy/joyplot.py
> +
If possible, a reasonable value for `x_range` should be set here. Otherwise it needs to be manually set in the external args (as you did in the notebook example).

2021-12-14 22:33 UTC, johnrsibert commented on joypy/joyplot.py
> +            sys.exit(1)
Done

2021-12-14 22:33 UTC, johnrsibert commented on joypy/joyplot.py
> +           sys.exit(1)
Done

2021-12-14 22:34 UTC, johnrsibert commented on joypy/joyplot.py
> +
Done

2021-12-14 22:34 UTC, johnrsibert commented on setup.py
> +      version='0.2.5.JS',
Done

2021-12-14 22:34 UTC, johnrsibert commented on joypy/__init__.py
> +__version__ = '0.2.5.JS'
Done

2021-12-14 22:34 UTC, johnrsibert commented on joypy/joyplot.py
> +
Done

2021-12-14 22:36 UTC, johnrsibert commented on joypy/joyplot.py
> +            floc=None,
Initially, I left these args as kwargs, but there were side effects. Other kind options threw exceptions.

2021-12-14 22:37 UTC, johnrsibert commented on tests/test_CFR.py
> +#!/usr/bin/env python3
Added code to pytest and removed test_CFR.py

2021-12-14 22:45 UTC, johnrsibert commented on joypy/joyplot.py
> +
The values x_range=[0.0,0.061] used in the example call to joyplot are specific to the example data. The values of x_range in plot_density are those assigned in the _x_range method, linspace( , , 1000)

2021-12-16 22:18 UTC, leotac approved these changes

2021-12-16 22:21 UTC, merged